name: custom_path
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  filesize: ^2.0.1
  colorize: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
